version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Extensions/Integration"
    schedule:
      interval: "daily"
      
  # This traces the dependencies through the dependency chain:
  # Generator3, GirModel, GirLoader
  - package-ecosystem: "nuget"
    directory: "/src/Generation/GirTool"
    schedule:
      interval: "daily"
